# Generated by Django 5.2.6 on 2025-09-14 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('personagens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolagemDado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('teste_atributo', 'Teste de Atributo'), ('teste_pericia', 'Teste de Perícia'), ('teste_resistencia', 'Teste de Resistência'), ('ataque', 'Rolagem de Ataque'), ('dano', 'Rolagem de Dano'), ('iniciativa', 'Iniciativa'), ('pontos_vida', 'Pontos de Vida'), ('custom', 'Rolagem Personalizada')], default='custom', max_length=20, verbose_name='Tipo')),
                ('modificador', models.CharField(choices=[('normal', 'Normal'), ('vantagem', 'Vantagem'), ('desvantagem', 'Desvantagem')], default='normal', max_length=15, verbose_name='Modificador')),
                ('expressao', models.CharField(help_text='Expressão da rolagem (ex: 1d20+5, 3d6)', max_length=200, verbose_name='Expressão')),
                ('resultados_individuais', models.JSONField(default=list, help_text='Lista dos resultados de cada dado', verbose_name='Resultados Individuais')),
                ('resultado_final', models.IntegerField(help_text='Resultado final da rolagem', verbose_name='Resultado Final')),
                ('resultado_bruto', models.IntegerField(help_text='Soma dos dados sem modificadores', verbose_name='Resultado Bruto')),
                ('modificador_valor', models.IntegerField(default=0, help_text='Valor do modificador aplicado (+/-)', verbose_name='Modificador Valor')),
                ('descricao', models.CharField(blank=True, help_text='Descrição do que está sendo testado', max_length=200, verbose_name='Descrição')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Informações adicionais (DC, contexto, etc.)', verbose_name='Metadados')),
                ('data_rolagem', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Rolagem')),
                ('publica', models.BooleanField(default=True, help_text='Visível para outros jogadores da campanha', verbose_name='Pública')),
                ('secreta', models.BooleanField(default=False, help_text='Apenas mestre pode ver o resultado', verbose_name='Secreta')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolagens', to='campanhas.campanha', verbose_name='Campanha')),
                ('personagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolagens', to='personagens.personagem', verbose_name='Personagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolagens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Rolagem de Dado',
                'verbose_name_plural': 'Rolagens de Dados',
                'ordering': ['-data_rolagem'],
                'indexes': [models.Index(fields=['usuario', 'campanha'], name='rolagem_rol_usuario_6e645a_idx'), models.Index(fields=['campanha', 'data_rolagem'], name='rolagem_rol_campanh_5f36fe_idx'), models.Index(fields=['personagem', 'tipo'], name='rolagem_rol_persona_c4f47d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateRolagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do template (ex: 'Ataque de Espada')", max_length=100, verbose_name='Nome')),
                ('expressao', models.CharField(help_text='Expressão da rolagem', max_length=200, verbose_name='Expressão')),
                ('tipo', models.CharField(choices=[('teste_atributo', 'Teste de Atributo'), ('teste_pericia', 'Teste de Perícia'), ('teste_resistencia', 'Teste de Resistência'), ('ataque', 'Rolagem de Ataque'), ('dano', 'Rolagem de Dano'), ('iniciativa', 'Iniciativa'), ('pontos_vida', 'Pontos de Vida'), ('custom', 'Rolagem Personalizada')], default='custom', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do que esse template faz', verbose_name='Descrição')),
                ('configuracoes', models.JSONField(default=dict, help_text='Configurações adicionais do template', verbose_name='Configurações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_rolagem', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Template de Rolagem',
                'verbose_name_plural': 'Templates de Rolagem',
                'ordering': ['nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
