[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn unified_chronicles.wsgi:application --host 0.0.0.0 --port $PORT"
