# Generated by Django 5.2.6 on 2025-09-14 18:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('personagens', '0002_initial'),
        ('rolagem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome personalizado da sala de chat', max_length=100, verbose_name='Nome da Sala')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da sala de chat', verbose_name='Descrição')),
                ('comandos_habilitados', models.BooleanField(default=True, help_text='Permitir comandos como /roll, /whisper', verbose_name='Comandos Habilitados')),
                ('rolagens_publicas', models.BooleanField(default=True, help_text='Exibir todas as rolagens no chat', verbose_name='Rolagens Públicas')),
                ('historico_visivel', models.BooleanField(default=True, help_text='Jogadores podem ver mensagens antigas', verbose_name='Histórico Visível')),
                ('max_mensagens_historico', models.PositiveIntegerField(default=1000, help_text='Limite de mensagens mantidas no histórico', verbose_name='Máx. Mensagens no Histórico')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sala_chat', to='campanhas.campanha', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False, help_text='Usuário está atualmente conectado', verbose_name='Online')),
                ('mutado', models.BooleanField(default=False, help_text='Usuário foi silenciado', verbose_name='Mutado')),
                ('is_moderador', models.BooleanField(default=False, help_text='Usuário pode moderar o chat', verbose_name='Moderador')),
                ('primeira_conexao', models.DateTimeField(auto_now_add=True, verbose_name='Primeira Conexão')),
                ('ultima_conexao', models.DateTimeField(auto_now=True, verbose_name='Ultima Conexão')),
                ('ultima_mensagem_vista', models.DateTimeField(blank=True, help_text='Timestamp da última mensagem visualizada', null=True, verbose_name='Ultima Mensagem Vista')),
                ('notificacoes_habilitadas', models.BooleanField(default=True, help_text='Receber notificações de mensagens', verbose_name='Notificações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_chat', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='mensagens.salachat', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Participação em Chat',
                'verbose_name_plural': 'Participações em Chat',
                'ordering': ['-ultima_conexao'],
                'unique_together': {('sala', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Mensagem Normal'), ('sistema', 'Mensagem do Sistema'), ('rolagem', 'Rolagem de Dados'), ('whisper', 'Mensagem Privada'), ('acao', 'Ação (/me)'), ('comando', 'Comando do Sistema'), ('entrada', 'Entrada de Jogador'), ('saida', 'Saída de Jogador')], default='normal', max_length=10, verbose_name='Tipo')),
                ('conteudo', models.TextField(help_text='Conteúdo da mensagem', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Conteúdo')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Dados adicionais da mensagem', verbose_name='Metadados')),
                ('editada', models.BooleanField(default=False, verbose_name='Editada')),
                ('timestamp_edicao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Edição')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('destinatario', models.ForeignKey(blank=True, help_text='Para mensagens privadas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('personagem', models.ForeignKey(blank=True, help_text='Personagem associado à mensagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_chat', to='personagens.personagem', verbose_name='Personagem')),
                ('rolagem', models.ForeignKey(blank=True, help_text='Rolagem associada à mensagem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_chat', to='rolagem.rolagemdado', verbose_name='Rolagem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='mensagens.salachat', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sala', 'timestamp'], name='mensagens_m_sala_id_5e178c_idx'), models.Index(fields=['usuario', 'tipo'], name='mensagens_m_usuario_5673f3_idx'), models.Index(fields=['sala', 'tipo', 'timestamp'], name='mensagens_m_sala_id_124c90_idx')],
            },
        ),
    ]
