# Generated by Django 5.2.6 on 2025-09-15 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_gm', '0001_initial'),
        ('personagens', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aguardando', 'Aguardando Seleção'), ('ativo', 'Ativo na Sessão'), ('pausado', 'Pausado'), ('saiu', 'Saiu da Sessão'), ('expulso', 'Expulso'), ('desconectado', 'Desconectado')], default='aguardando', max_length=20, verbose_name='Estado')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, help_text='Quando o usuário entrou na sessão', verbose_name='Data de Entrada')),
                ('data_selecao_personagem', models.DateTimeField(blank=True, help_text='Quando o personagem foi selecionado', null=True, verbose_name='Data de Seleção do Personagem')),
                ('data_ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('bloqueado_ate', models.DateTimeField(blank=True, help_text='Se definido, usuário não pode trocar personagem até esta data', null=True, verbose_name='Bloqueado até')),
                ('pode_trocar_personagem', models.BooleanField(default=False, help_text='Se o mestre permite troca de personagem durante a sessão', verbose_name='Pode Trocar Personagem')),
                ('observacoes', models.TextField(blank=True, help_text='Notas do mestre ou sistema sobre esta participação', verbose_name='Observações')),
                ('personagem', models.ForeignKey(blank=True, help_text='Personagem controlado pelo usuário nesta sessão', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_sessao', to='personagens.personagem', verbose_name='Personagem')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='ia_gm.sessaoia', verbose_name='Sessão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_sessao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante de Sessão',
                'verbose_name_plural': 'Participantes de Sessão',
                'ordering': ['data_entrada'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='usuarios_se_usuario_e8f2ea_idx'), models.Index(fields=['sessao', 'estado'], name='usuarios_se_sessao__4e0a4c_idx'), models.Index(fields=['personagem', 'estado'], name='usuarios_se_persona_14a1e3_idx'), models.Index(fields=['data_entrada'], name='usuarios_se_data_en_dfc3e8_idx')],
                'unique_together': {('usuario', 'sessao')},
            },
        ),
    ]
