# Generated by Django 5.2.6 on 2025-09-14 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da campanha', max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Descrição e sinôpse da campanha', verbose_name='Descrição')),
                ('nivel_inicial', models.PositiveSmallIntegerField(default=1, help_text='Nível inicial dos personagens', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nível Inicial')),
                ('nivel_maximo', models.PositiveSmallIntegerField(default=20, help_text='Nível máximo da campanha', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nível Máximo')),
                ('max_jogadores', models.PositiveSmallIntegerField(default=6, help_text='Número máximo de jogadores', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Máx. Jogadores')),
                ('ia_ativa', models.BooleanField(default=True, help_text='Usar IA como Game Master', verbose_name='IA GM Ativa')),
                ('configuracoes_ia', models.JSONField(default=dict, help_text='Configurações comportamentais da IA GM', verbose_name='Configurações da IA')),
                ('personalidade_gm', models.JSONField(default=dict, help_text='Traços de personalidade do GM artificial', verbose_name='Personalidade do GM')),
                ('estado', models.CharField(choices=[('planejamento', 'Em Planejamento'), ('ativa', 'Ativa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='planejamento', max_length=20, verbose_name='Estado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data da primeira sessão', null=True, verbose_name='Data de Início')),
                ('data_ultima_sessao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sessão')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('configuracoes_gerais', models.JSONField(default=dict, help_text='Regras da casa e configurações especiais', verbose_name='Configurações Gerais')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='ConviteCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=15, verbose_name='Estado')),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem personalizada do convite', verbose_name='Mensagem')),
                ('data_convite', models.DateTimeField(auto_now_add=True, verbose_name='Data do Convite')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('data_expiracao', models.DateTimeField(help_text='Convite expira automaticamente', verbose_name='Data de Expiração')),
            ],
            options={
                'verbose_name': 'Convite para Campanha',
                'verbose_name_plural': 'Convites para Campanhas',
                'ordering': ['-data_convite'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('ativo', models.BooleanField(default=True, help_text='Participante ativo na campanha', verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações sobre a participação', verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Participação em Campanha',
                'verbose_name_plural': 'Participações em Campanhas',
                'ordering': ['data_entrada'],
            },
        ),
    ]
