# Generated by Django 5.2.6 on 2025-09-14 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('sistema_unificado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='mestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_mestradas', to=settings.AUTH_USER_MODEL, verbose_name='Mestre'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='sistema_jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_unificado.sistemajogo', verbose_name='Sistema de Jogo'),
        ),
        migrations.AddField(
            model_name='convitecampanha',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='campanhas.campanha', verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='convitecampanha',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Convidado'),
        ),
        migrations.AddField(
            model_name='convitecampanha',
            name='convidado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por'),
        ),
        migrations.AddField(
            model_name='participacaocampanha',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='campanhas.campanha', verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='participacaocampanha',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='jogadores',
            field=models.ManyToManyField(related_name='campanhas_participando', through='campanhas.ParticipacaoCampanha', to=settings.AUTH_USER_MODEL, verbose_name='Jogadores'),
        ),
        migrations.AlterUniqueTogether(
            name='convitecampanha',
            unique_together={('campanha', 'convidado')},
        ),
        migrations.AlterUniqueTogether(
            name='participacaocampanha',
            unique_together={('usuario', 'campanha')},
        ),
    ]
