# Generated by Django 5.2.6 on 2025-09-15 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_finalize_organizador_transition'),
        ('personagens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('banido', 'Banido'), ('aguardando', 'Aguardando Aprovação'), ('pendente', 'Pendente de Personagem')], default='pendente', help_text='Status atual da participação na campanha', max_length=20, verbose_name='Status')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, help_text='Quando o usuário se juntou à campanha', verbose_name='Data de Entrada')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Última vez que o registro foi modificado', verbose_name='Última Atualização')),
                ('data_saida', models.DateTimeField(blank=True, help_text='Quando o usuário deixou a campanha (se aplicável)', null=True, verbose_name='Data de Saída')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a participação do usuário', verbose_name='Observações')),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Quando a participação foi aprovada', null=True, verbose_name='Data de Aprovação')),
                ('personagem_ativo', models.BooleanField(default=True, help_text='Se o personagem está ativo nesta campanha', verbose_name='Personagem Ativo')),
                ('experiencia_ganha', models.PositiveIntegerField(default=0, help_text='XP ganha pelo personagem nesta campanha', verbose_name='Experiência Ganha')),
                ('aprovado_por', models.ForeignKey(blank=True, help_text='Usuário que aprovou a participação (organizador da campanha)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_campanha_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado Por')),
                ('campanha', models.ForeignKey(help_text='Campanha onde o usuário participa', on_delete=django.db.models.deletion.CASCADE, related_name='participantes_personagens', to='campanhas.campanha', verbose_name='Campanha')),
                ('personagem', models.ForeignKey(blank=True, help_text='Personagem usado pelo usuário nesta campanha', null=True, on_delete=django.db.models.deletion.CASCADE, to='personagens.personagem', verbose_name='Personagem')),
                ('usuario', models.ForeignKey(help_text='Usuário que participa da campanha', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante da Campanha',
                'verbose_name_plural': 'Participantes das Campanhas',
                'ordering': ['data_entrada'],
                'indexes': [models.Index(fields=['usuario', 'campanha'], name='campanhas_c_usuario_a3049d_idx'), models.Index(fields=['personagem', 'campanha'], name='campanhas_c_persona_0512ad_idx'), models.Index(fields=['status'], name='campanhas_c_status_c0c004_idx'), models.Index(fields=['data_entrada'], name='campanhas_c_data_en_429973_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ativo', 'aguardando', 'pendente'])), fields=('usuario', 'campanha'), name='unique_user_per_campaign'), models.UniqueConstraint(condition=models.Q(('personagem__isnull', False), ('status__in', ['ativo', 'aguardando'])), fields=('personagem', 'campanha'), name='unique_character_per_campaign')],
            },
        ),
    ]
