# Generated by Django 5.2.6 on 2025-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0006_campaignparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='publica',
            field=models.BooleanField(default=False, help_text='Indica se a campanha é pública e visível para todos os usuários.', verbose_name='Pública'),
        ),
    ]
