# Generated by Django 5.2.6 on 2025-09-14 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('personagens', '0001_initial'),
        ('sistema_unificado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopersonagem',
            name='usuario_mudanca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fez a mudança'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='campanhas.campanha', verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='sistema_jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_unificado.sistemajogo', verbose_name='Sistema de Jogo'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='historicopersonagem',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='personagens.personagem', verbose_name='Personagem'),
        ),
        migrations.AddField(
            model_name='backuppersonagem',
            name='personagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='personagens.personagem', verbose_name='Personagem'),
        ),
        migrations.AddIndex(
            model_name='personagem',
            index=models.Index(fields=['usuario', 'campanha'], name='personagens_usuario_93ae88_idx'),
        ),
        migrations.AddIndex(
            model_name='personagem',
            index=models.Index(fields=['campanha', 'ativo'], name='personagens_campanh_87ab20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backuppersonagem',
            unique_together={('personagem', 'versao')},
        ),
    ]
