# Generated by Django 5.2.6 on 2025-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='aparencia',
            field=models.TextField(blank=True, help_text='Descrição da aparência do personagem', verbose_name='Aparência Física'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='habilidades',
            field=models.TextField(blank=True, verbose_name='Habilidades Especiais'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='idade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='ideais',
            field=models.TextField(blank=True, verbose_name='Ideais & Motivações'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
