# Generated by Django 5.2.6 on 2025-09-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0003_personagem_altura_personagem_aparencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='aparencia',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='ideais',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='peso',
        ),
    ]
