# Generated by Django 5.2.6 on 2025-09-15 00:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personagens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome da sessão de jogo', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da sessão', verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('ativa', models.BooleanField(default=True, help_text='Se a sessão está ativa e aceita participantes', verbose_name='Ativa')),
                ('max_participantes', models.PositiveIntegerField(default=6, help_text='Número máximo de jogadores na sessão', verbose_name='Máximo de Participantes')),
                ('mestre', models.ForeignKey(help_text='Usuário que conduzirá a sessão', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mestre')),
            ],
            options={
                'verbose_name': 'Sessão de Jogo',
                'verbose_name_plural': 'Sessões de Jogo',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('banido', 'Banido'), ('aguardando', 'Aguardando Aprovação')], default='aguardando', help_text='Status atual da participação na sessão', max_length=20, verbose_name='Status')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, help_text='Quando o usuário se juntou à sessão', verbose_name='Data de Entrada')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Última vez que o registro foi modificado', verbose_name='Última Atualização')),
                ('data_saida', models.DateTimeField(blank=True, help_text='Quando o usuário deixou a sessão (se aplicável)', null=True, verbose_name='Data de Saída')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a participação do usuário', verbose_name='Observações')),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Quando a participação foi aprovada', null=True, verbose_name='Data de Aprovação')),
                ('aprovado_por', models.ForeignKey(blank=True, help_text='Usuário que aprovou a participação (normalmente o mestre)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado Por')),
                ('personagem', models.ForeignKey(help_text='Personagem que será usado na sessão', on_delete=django.db.models.deletion.CASCADE, to='personagens.personagem', verbose_name='Personagem')),
                ('sessao', models.ForeignKey(help_text='Sessão de jogo onde o usuário participará', on_delete=django.db.models.deletion.CASCADE, to='sessoes.sessaojogo', verbose_name='Sessão')),
                ('usuario', models.ForeignKey(help_text='Usuário que participará da sessão', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante da Sessão',
                'verbose_name_plural': 'Participantes das Sessões',
                'ordering': ['data_entrada'],
                'indexes': [models.Index(fields=['usuario', 'sessao'], name='sessoes_ses_usuario_75ed5d_idx'), models.Index(fields=['personagem', 'sessao'], name='sessoes_ses_persona_981a39_idx'), models.Index(fields=['status'], name='sessoes_ses_status_4fcb73_idx'), models.Index(fields=['data_entrada'], name='sessoes_ses_data_en_561ef3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ativo', 'aguardando'])), fields=('usuario', 'sessao'), name='unique_user_per_session'), models.UniqueConstraint(condition=models.Q(('status__in', ['ativo', 'aguardando'])), fields=('personagem', 'sessao'), name='unique_character_per_session')],
            },
        ),
    ]
