# Generated by Django 5.2.6 on 2025-09-14 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('personagens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaLongoPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('DECISAO', 'Decisão Importante'), ('CONSEQUENCIA', 'Consequência de Ação'), ('RELACIONAMENTO', 'Mudança de Relacionamento'), ('DESCOBERTA', 'Descoberta Significativa'), ('CONQUISTA', 'Conquista/Vitória'), ('PERDA', 'Perda/Derrota'), ('MUDANCA_MUNDO', 'Mudança no Mundo')], max_length=20)),
                ('impacto_narrativo', models.TextField(help_text='Como este evento afeta a narrativa futura')),
                ('consequencias_pendentes', models.TextField(blank=True, help_text='Consequências que ainda não se manifestaram')),
                ('importancia', models.IntegerField(choices=[(1, 'Trivial'), (2, 'Menor'), (3, 'Moderada'), (4, 'Grande'), (5, 'Épica')], default=3)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_evento', models.DateTimeField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias_ia', to='campanhas.campanha')),
                ('personagens_envolvidos', models.ManyToManyField(blank=True, to='personagens.personagem')),
            ],
            options={
                'verbose_name': 'Memória de Longo Prazo',
                'verbose_name_plural': 'Memórias de Longo Prazo',
                'ordering': ['-importancia', '-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='SessaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome/título da sessão', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou resumo da sessão')),
                ('estilo_narrativo', models.CharField(choices=[('EPICO', 'Épico e Grandioso'), ('MISTERIOSO', 'Misterioso e Intrigante'), ('SOMBRIO', 'Sombrio e Gótico'), ('HEROICO', 'Heroico e Inspirador'), ('COMICO', 'Cômico e Leviano'), ('REALISTA', 'Realista e Crível'), ('ROMANTICO', 'Romântico e Emotivo'), ('HORROR', 'Terror e Suspense')], default='EPICO', help_text='Estilo narrativo predominante', max_length=20)),
                ('criatividade_nivel', models.IntegerField(default=7, help_text='Nível de criatividade (1-10)')),
                ('dificuldade_nivel', models.IntegerField(default=5, help_text='Nível de dificuldade dos desafios (1-10)')),
                ('ativa', models.BooleanField(default=False)),
                ('contexto_atual', models.JSONField(default=dict, help_text='Contexto atual da sessão (locais, NPCs presentes, etc.)')),
                ('memoria_curto_prazo', models.JSONField(default=list, help_text='Memória de curto prazo (últimas 10-20 interações)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('total_interacoes', models.PositiveIntegerField(default=0)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_ia', to='campanhas.campanha')),
            ],
            options={
                'verbose_name': 'Sessão de IA',
                'verbose_name_plural': 'Sessões de IA',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='NPCGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulo', models.CharField(blank=True, help_text='Título ou apelido', max_length=100)),
                ('raca', models.CharField(blank=True, max_length=50)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('ocupacao', models.CharField(blank=True, max_length=100)),
                ('descricao_fisica', models.TextField(help_text='Aparência física detalhada')),
                ('idade_aparente', models.CharField(blank=True, max_length=50)),
                ('motivacao_principal', models.TextField(help_text='Motivação clara do NPC')),
                ('falha_personalidade', models.TextField(help_text='Falha ou fraqueza de personalidade')),
                ('segredo', models.TextField(help_text='Segredo que o NPC guarda')),
                ('maneirismos', models.TextField(blank=True, help_text='Maneirismos únicos')),
                ('padrao_fala', models.TextField(blank=True, help_text='Como fala (sotaque, gírias, etc.)')),
                ('vocabulario', models.TextField(blank=True, help_text='Palavras e frases características')),
                ('aliados', models.TextField(blank=True, help_text='Aliados e amigos')),
                ('inimigos', models.TextField(blank=True, help_text='Inimigos e rivais')),
                ('familia', models.TextField(blank=True, help_text='Família e parentes')),
                ('nivel_poder', models.IntegerField(default=1, help_text='Nível aproximado de poder')),
                ('recursos', models.TextField(blank=True, help_text='Recursos disponíveis')),
                ('influencia', models.TextField(blank=True, help_text='Influência política/social')),
                ('localizacao_atual', models.CharField(blank=True, max_length=100)),
                ('disposicao', models.CharField(choices=[('AMIGAVEL', 'Amigável'), ('NEUTRO', 'Neutro'), ('HOSTIL', 'Hostil'), ('SUSPEITO', 'Suspeito'), ('INTERESSADO', 'Interessado')], default='NEUTRO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('primeiro_encontro', models.BooleanField(default=True)),
                ('interacoes_count', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_interacao', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs_ia', to='campanhas.campanha')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='ia_gm.sessaoia')),
            ],
            options={
                'verbose_name': 'NPC Gerado',
                'verbose_name_plural': 'NPCs Gerados',
                'ordering': ['-data_ultima_interacao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interacao', models.CharField(choices=[('NARRATIVA', 'Narrativa'), ('NPC', 'Personagem Não Jogável'), ('LOCAL', 'Local/Cenário'), ('MISSAO', 'Missão/Quest'), ('ITEM', 'Item/Artefato'), ('MONSTRO', 'Criatura/Monstro'), ('EVENTO', 'Evento/Acontecimento'), ('DIALOGO', 'Diálogo/Conversa'), ('ENIGMA', 'Enigma/Puzzle'), ('RECOMPENSA', 'Recompensa/Tesouro')], max_length=20)),
                ('prompt_usuario', models.TextField(help_text='O que o usuário/jogador pediu')),
                ('contexto', models.JSONField(default=dict, help_text='Contexto usado para gerar a resposta')),
                ('resposta_ia', models.TextField(help_text='Resposta gerada pela IA')),
                ('tokens_usados', models.PositiveIntegerField(default=0)),
                ('tempo_geracao', models.FloatField(default=0.0, help_text='Tempo de geração em segundos')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('avaliacao_usuario', models.IntegerField(blank=True, choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito Bom'), (5, '5 - Excelente')], help_text='Avaliação do usuário sobre a resposta', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback detalhado do usuário')),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_ia', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='ia_gm.sessaoia')),
            ],
            options={
                'verbose_name': 'Interação com IA',
                'verbose_name_plural': 'Interações com IA',
                'ordering': ['-data_interacao'],
            },
        ),
    ]
